experiment_name: H2
mode: standard
parent:
  resistant:
    name: P557
    R1: ../reads/ERR2775635_1.fastq.gz
    R2: ../reads/ERR2775635_2.fastq.gz
  susceptible:
    name: Picasso
    R1: ../reads/ERR2775636_1.fastq.gz
    R2: ../reads/ERR2775636_2.fastq.gz
bulk:
  resistant:
    R1: ../reads/ERR2775637_1.fastq.gz
    R2: ../reads/ERR2775637_2.fastq.gz
  susceptible:
    R1: ../reads/ERR2775638_1.fastq.gz
    R2: ../reads/ERR2775638_2.fastq.gz
reference:
  name: P557
  fasta: ../canu/p557.contigs.fasta
allele_frequency:
  parent:
    susceptible:
      min: 95
      max: 100
    resistant:
      min: 0
      max: 5
  bulk:
    susceptible:
      min: 95
      max: 100
    resistant:
      min: 20
      max: 30
bowtie2_args: "--score-min L,-0.18,-0.18 --phred33 --fr --maxins 1000 --very-sensitive --no-unal --no-discordant"